export type HeritageItem = {
  id: string;
  title: string;
  province: string;
  category: string;
  type: 'tangible' | 'intangible';
  subtitle: string;
  body: string;
  tag: string;
  description: string;
  highlights: string[];
  coverImage?: string;
  gallery?: string[];
  createdAt?: string;
  location?: {
    lat?: number;
    lng?: number;
  } | null;
  builtYear?: string | number;
};

export const heritageItems: HeritageItem[] = [
  {
    id: 'chua-som-rong',
    title: 'Chùa Som Rông',
    province: 'Sóc Trăng',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Khmer với bảo tháp uy nghi và tượng Phật nằm 63 mét.',
    body: 'Chùa Som Rông (Wat Pătum Wôngsa Som Rông) tọa lạc tại phường 5, thành phố Sóc Trăng. Ngôi chùa có lịch sử hàng trăm năm, nổi bật với bảo tháp cao 32 mét lộng lẫy sơn màu xám hiện đại và tượng Phật Thích Ca nhập Niết bàn ngoài trời dài 63 mét, cao 22.5 mét. Kiến trúc chùa là kiệt tác nghệ thuật điêu khắc hoa văn Khmer tinh xảo, thể hiện nét văn hóa Phật giáo Nam tông đặc trưng.',
    tag: 'Nổi bật',
    description: 'Ngôi chùa tiêu biểu của tỉnh Sóc Trăng sở hữu tượng Phật nằm lớn nhất Việt Nam.',
    highlights: ['Tượng Phật nằm 63m ngoài trời', 'Tòa bảo tháp xám uy nghi', 'Kiến trúc điêu khắc chạm trổ tinh xảo'],
    coverImage: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1608958416733-1492ba666e5f?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1548625361-155deee223c2?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:00:00.000Z',
    location: { lat: 9.6092, lng: 105.9811 },
    builtYear: 'Thế kỷ XV',
  },
  {
    id: 'chua-doi',
    title: 'Chùa Dơi (Mã Tộc)',
    province: 'Sóc Trăng',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Di tích quốc gia cổ kính hơn 400 tuổi và đàn dơi tự nhiên.',
    body: 'Chùa Dơi (Wat Mahatup) tọa lạc tại thành phố Sóc Trăng, tỉnh Sóc Trăng. Đây là di tích lịch sử - văn hóa cấp quốc gia xây dựng từ thế kỷ XVI. Ngôi chùa mang đậm phong cách kiến trúc chùa Khmer truyền thống với mái ngói cong đuôi rồng Naga vàng rực rỡ. Nơi đây nổi tiếng vì là nơi cư ngụ tự nhiên của hàng vạn con dơi ngựa quý hiếm treo mình trên những tán cây cổ thụ trong khuôn viên chùa.',
    tag: 'Khám phá',
    description: 'Ngôi chùa cổ kính linh thiêng nổi tiếng gắn liền với đàn dơi quạ tự nhiên sinh sống.',
    highlights: ['Khuôn viên dơi tự nhiên trú ngụ', 'Kiến trúc Mahatup cổ kính 400 năm', 'Hệ thống bích họa cổ trong chánh điện'],
    coverImage: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1566121933407-3c7ccdd26763?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:05:00.000Z',
    location: { lat: 9.5775, lng: 105.9728 },
    builtYear: 'Thế kỷ XVI',
  },
  {
    id: 'chua-chantarangsay',
    title: 'Chùa Chantarangsay',
    province: 'TP. Hồ Chí Minh',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Khmer đầu tiên và là trung tâm văn hóa giữa lòng đô thị.',
    body: 'Chùa Chantarangsay (Wat Candaransĩ) nằm tại Quận 3, TP. Hồ Chí Minh, được xây dựng năm 1946. Là ngôi chùa Khmer đầu tiên được xây dựng tại thành phố, chùa đóng vai trò là điểm sinh hoạt tôn giáo, tín ngưỡng và văn hóa lễ hội lớn của toàn bộ đồng bào người Khmer Nam Bộ đang sinh sống học tập tại TP.HCM.',
    tag: 'Nổi bật',
    description: 'Ngôi chùa Phật giáo Nam tông Khmer duy nhất và lâu đời bậc nhất giữa trung tâm TP.HCM.',
    highlights: ['Ngôi chùa Khmer đầu tiên tại TP.HCM', 'Mái chồng nhiều tầng uốn rồng Naga', 'Địa điểm sinh hoạt văn hóa lễ hội Khmer đô thị'],
    coverImage: 'https://images.unsplash.com/photo-1566121933407-3c7ccdd26763?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1566121933407-3c7ccdd26763?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1598908313407-4fbd48db2c96?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1507666400095-46726aa17986?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:10:00.000Z',
    location: { lat: 10.7905, lng: 106.6806 },
    builtYear: '1946',
  },
  {
    id: 'chua-hang',
    title: 'Chùa Hang',
    province: 'Trà Vinh',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Kompong Chrây với cổng hang đá độc đáo và xưởng khắc gỗ.',
    body: 'Chùa Hang (Wat Kompong Chrây) tọa lạc tại huyện Châu Thành, tỉnh Trà Vinh. Chùa nổi tiếng với chiếc cổng phụ độc đáo được xây dựng giống như lối vào một hang đá thiên nhiên sâu thẳm. Khuôn viên chùa là một cánh rừng sao dầu rộng lớn rợp bóng mát, nơi lưu giữ xưởng khắc điêu khắc gỗ thủ công từ những gốc cây khô của các nhà sư.',
    tag: 'Khám phá',
    description: 'Chùa nổi bật với cổng hang tự nhiên độc lạ và nghề khắc gỗ nghệ thuật lâu năm.',
    highlights: ['Chiếc cổng hình hang đá độc đáo', 'Nghề khắc gỗ mỹ nghệ từ gốc cây khô', 'Rừng cây sao dầu rộng lớn'],
    coverImage: 'https://images.unsplash.com/photo-1542856391-010fb87dcfed?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1542856391-010fb87dcfed?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1608976478549-3652f4007b7b?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:15:00.000Z',
    location: { lat: 9.8789, lng: 106.3123 },
    builtYear: '1637',
  },
  {
    id: 'chua-ghositaram',
    title: 'Chùa Ghositaram',
    province: 'Bạc Liêu',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Kiệt tác mỹ thuật chánh điện Khmer rực rỡ và lớn nhất Việt Nam.',
    body: 'Chùa Ghositaram tại huyện Vĩnh Lợi, tỉnh Bạc Liêu được hoàn thành chánh điện mới năm 2010. Đây là ngôi chánh điện lớn nhất và rực rỡ nhất trong hệ thống chùa Khmer Việt Nam, mang màu sắc đỏ vàng đặc trưng và những đường nét điêu khắc, chạm trổ phù điêu nổi sống động của nghệ nhân dân gian Khmer.',
    tag: 'Nổi bật',
    description: 'Chánh điện chùa Khmer lớn và rực rỡ bậc nhất miền Tây Nam Bộ.',
    highlights: ['Chánh điện Khmer quy mô lớn nhất Việt Nam', 'Màu sắc đỏ vàng rực rỡ nổi bật', 'Họa tiết chim thần Krud nâng đỡ mái'],
    coverImage: 'https://images.unsplash.com/photo-1598908313407-4fbd48db2c96?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1598908313407-4fbd48db2c96?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:20:00.000Z',
    location: { lat: 9.3082, lng: 105.7489 },
    builtYear: '1860',
  },
  {
    id: 'le-hoi-ooc-om-bok',
    title: 'Lễ hội Oóc Om Bóc',
    province: 'Sóc Trăng',
    category: 'Lễ hội truyền thống',
    type: 'intangible',
    subtitle: 'Lễ hội cúng trăng tạ ơn và giải đua ghe ngo rực lửa trên sông.',
    body: 'Lễ hội Oóc Om Bóc (Lễ cúng Trăng) diễn ra vào đêm rằm tháng 10 âm lịch khi mùa mưa kết thúc. Đây là Di sản văn hóa phi vật thể quốc gia quan trọng bậc nhất của đồng bào Khmer Nam Bộ nhằm tạ ơn thần Mặt Trăng đã ban mùa màng tươi tốt. Lễ hội đặc sắc với hội đua ghe ngo độc mộc thu hút hàng chục đội chèo tranh tài trên sông Maspero.',
    tag: 'Mới',
    description: 'Lễ hội lớn bậc nhất vùng Nam Bộ được công nhận là Di sản phi vật thể quốc gia.',
    highlights: ['Nghi thức cúng trăng đút cốm dẹp', 'Đua ghe ngo truyền thống rực rỡ', 'Hội thả đèn nước Lôi Pro-têp trên sông'],
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1524412529636-bb435f6c2d1d?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1530128118208-89f9e73c4d7f?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:25:00.000Z',
    location: { lat: 9.6008, lng: 105.9745 },
  },
  {
    id: 'le-hoi-sene-dolta',
    title: 'Lễ hội Sene Dolta',
    province: 'An Giang',
    category: 'Lễ hội truyền thống',
    type: 'intangible',
    subtitle: 'Lễ cúng tế báo hiếu tổ tiên và hội đua bò Bảy Núi kịch tính.',
    body: 'Lễ hội Sene Dolta (lễ cúng ông bà) của người Khmer diễn ra vào cuối tháng 8 âm lịch hằng năm. Lễ hội thể hiện truyền thống uống nước nhớ nguồn, lòng hiếu thảo của con cháu đối với ông bà tổ tiên đã khuất. Tại vùng Bảy Núi (An Giang), lễ hội gắn liền với hội đua bò truyền thống kịch tính đầy kịch tính thu hút đông đảo du khách.',
    tag: 'Xem nhanh',
    description: 'Lễ báo hiếu tổ tiên ấm áp kết hợp hội đua bò Bảy Núi vang danh Nam Bộ.',
    highlights: ['Nghi lễ cúng báo hiếu tổ tiên tại gia định', 'Hội đua bò Bảy Núi nghẹt thở kịch tính', 'Ẩm thực bánh gừng, canh sim-lo đặc sắc'],
    coverImage: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1568043210943-0e8aac4b9734?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1598866594230-a7c12756260f?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:30:00.000Z',
    location: { lat: 10.4282, lng: 105.0256 },
  },
  {
    id: 'nghe-thuat-ro-bam',
    title: 'Nghệ thuật Rô Băm',
    province: 'Trà Vinh',
    category: 'Nghệ thuật biểu diễn',
    type: 'intangible',
    subtitle: 'Sân khấu kịch múa cổ điển truyền thuyết sử thi Reamker thần thoại.',
    body: 'Nghệ thuật Rô Băm là loại hình sân khấu múa cổ điển cung đình lâu đời của đồng bào Khmer. Diễn viên sử dụng ngôn ngữ điệu múa uốn cong cơ thể Apsara và đeo mặt nạ gỗ tinh xảo hóa thân thành hoàng tử Preah Ream, khỉ thần Hanuman, quỷ vương kể lại sử thi Reamker nhằm răn dạy đạo lý làm người sâu sắc.',
    tag: 'Nổi bật',
    description: 'Di sản kịch múa cổ truyền quý hiếm được bảo tồn khẩn cấp của người Khmer.',
    highlights: ['Các vũ điệu kịch múa sử thi Reamker', 'Mặt nạ gỗ điêu khắc sơn son thếp vàng', 'Dàn nhạc ngũ âm Pinpeat đệm trầm bổng'],
    coverImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:35:00.000Z',
    location: { lat: 9.9347, lng: 106.3456 },
  },
  {
    id: 'le-hoi-kathina',
    title: 'Lễ hội Kathina',
    province: 'Sóc Trăng',
    category: 'Lễ hội truyền thống',
    type: 'intangible',
    subtitle: 'Lễ dâng y phục cà sa cúng dường chư tăng sau mùa an cư.',
    body: 'Lễ hội Kathina (Lễ dâng y cà sa) diễn ra trong 1 tháng từ rằm tháng 9 đến rằm tháng 10 âm lịch sau mùa an cư kiết hạ. Phật tử quyên góp và diễu hành dâng cúng y phục cà sa mới cùng vật dụng sinh hoạt cúng dường lên các vị sư sãi để cầu phước đức bình an và thịnh vượng cho phum sóc.',
    tag: 'Sự kiện',
    description: 'Nghi lễ dâng y tôn giáo linh thiêng và lớn nhất của Phật giáo Nam tông Khmer.',
    highlights: ['Nghi thức dâng y cà sa cúng dường trang trọng', 'Diễu hành xe hoa phum sóc nhộn nhịp', 'Quyên góp tu sửa cơ sở vật chất chùa chiền'],
    coverImage: 'https://images.unsplash.com/photo-1608976478549-3652f4007b7b?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1608976478549-3652f4007b7b?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1542856391-010fb87dcfed?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1507666400095-46726aa17986?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:40:00.000Z',
    location: { lat: 9.6012, lng: 105.9734 },
  },
  {
    id: 'nghe-thuat-chapei-don-ca',
    title: 'Nghệ thuật Chapei Don Ca',
    province: 'Sóc Trăng',
    category: 'Nghệ thuật biểu diễn',
    type: 'intangible',
    subtitle: 'Hát kể tự sự độc tấu đàn Chapey hai dây điêu luyện.',
    body: 'Nghệ thuật Chapei Don Ca (Chapey Dong Veng) là di sản phi vật thể nhân loại được UNESCO công nhận. Người nghệ nhân vừa tự gảy chiếc đàn Chapey hai dây thùng vuông cần dài đặc trưng, vừa ứng khẩu hát tự sự kể về các câu chuyện lịch sử phum sóc, giáo dục đạo đức và răn dạy con cháu.',
    tag: 'Nổi bật',
    description: 'Di sản phi vật thể nhân loại UNESCO tôn vinh lối hát tự sự dân gian độc đáo.',
    highlights: ['Độc tấu đàn Chapey hai dây cần dài', 'Lối hát tự sự ứng khẩu sâu sắc', 'Tác phẩm ca ngợi tình yêu quê hương lao động'],
    coverImage: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=600&q=80'
    ],
    createdAt: '2026-06-04T08:45:00.000Z',
    location: { lat: 9.5823, lng: 105.9612 },
  },
  {
    id: 'chua-ang',
    title: 'Chùa Âng (Wat Angkor Raig Borei)',
    province: 'Trà Vinh',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa cổ kính tiêu biểu bậc nhất Trà Vinh xây dựng năm 990.',
    body: 'Chùa Âng tọa lạc tại phường 8, thành phố Trà Vinh, nằm trong khuôn viên di tích Ao Bà Om rộng lớn. Đây là ngôi chùa cổ kính bậc nhất của hệ thống chùa Khmer Trà Vinh, được xây dựng từ thế kỷ X (năm 990). Chùa mang đậm kiến trúc Angkor cổ với mái nhiều tầng cong vút điêu khắc hình tượng rồng Naga, chim thần Krud nâng mái vô cùng trang trọng.',
    tag: 'Nổi bật',
    description: 'Ngôi chùa cổ kính 1000 năm tuổi gắn liền với danh thắng Ao Bà Om của Trà Vinh.',
    highlights: ['Xây dựng từ năm 990 cổ kính', 'Nằm cạnh danh thắng Ao Bà Om', 'Kiến trúc Angkor chạm trổ tinh xảo'],
    createdAt: '2026-06-04T08:46:00.000Z',
    location: { lat: 9.9405, lng: 106.3768 },
    builtYear: 'Năm 990',
  },
  {
    id: 'chua-khleang',
    title: "Chùa Kh'leang",
    province: 'Sóc Trăng',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa cổ gắn liền với lịch sử hình thành vùng đất Sóc Trăng.',
    body: "Chùa Kh'leang tọa lạc tại phường 6, thành phố Sóc Trăng, được xây dựng vào khoảng năm 1532. Đây là một trong những ngôi chùa Khmer cổ nhất tỉnh Sóc Trăng. Kiến trúc chùa thể hiện sự giao thoa văn hóa độc đáo giữa Khmer Nam Bộ kết hợp với một vài chi tiết hoa văn trang trí của người Kinh và Hoa.",
    tag: 'Cổ kính',
    description: 'Di tích lịch sử cấp quốc gia có tuổi đời gần 500 năm tại trung tâm Sóc Trăng.',
    highlights: ['Xây dựng năm 1532', 'Giao thoa văn hóa Khmer - Kinh - Hoa', 'Khuôn viên rợp bóng cây cổ thụ'],
    createdAt: '2026-06-04T08:47:00.000Z',
    location: { lat: 9.6053, lng: 105.9782 },
    builtYear: '1532',
  },
  {
    id: 'chua-chen-kieu',
    title: 'Chùa Chén Kiểu (Wat Sà Lôn)',
    province: 'Sóc Trăng',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa độc đáo ốp bằng hàng triệu mảnh chén đĩa sứ sắc sảo.',
    body: 'Chùa Chén Kiểu (Wat Sà Lôn) nằm trên Quốc lộ 1A, thuộc huyện Mỹ Xuyên, tỉnh Sóc Trăng. Điểm nổi bật nhất của ngôi chùa là toàn bộ tường chánh điện, các tòa tháp và lan can đều được trang trí, ốp bằng những mảnh chén, đĩa, tô sứ hoa văn vô cùng rực rỡ, tạo nên một kiệt tác nghệ thuật kiến trúc độc nhất vô nhị.',
    tag: 'Độc đáo',
    description: 'Ngôi chùa nổi tiếng miền Tây được trang trí từ hàng triệu mảnh sứ sắc màu.',
    highlights: ['Ốp mảnh chén đĩa sứ độc đáo', 'Mái chánh điện ba tầng rực rỡ', 'Khuôn viên chùa rộng lớn thoáng đãng'],
    createdAt: '2026-06-04T08:48:00.000Z',
    location: { lat: 9.5167, lng: 105.9833 },
    builtYear: '1815',
  },
  {
    id: 'chua-xiem-can',
    title: 'Chùa Xiêm Cán',
    province: 'Bạc Liêu',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Khmer lớn và lộng lẫy nhất khu vực ven biển Bạc Liêu.',
    body: 'Chùa Xiêm Cán thuộc xã Vĩnh Trạch Đông, thành phố Bạc Liêu. Được xây dựng năm 1887, chùa mang phong cách kiến trúc Angkor tinh xảo với quy mô rộng lớn. Cổng chùa, hàng rào, chánh điện và tháp cốt được điêu khắc hoa văn Naga rực rỡ sắc màu, nổi bật giữa vùng ven biển lộng gió.',
    tag: 'Nổi bật',
    description: 'Công trình tôn giáo Angkor nguy nga tráng lệ thu hút du khách hàng đầu Bạc Liêu.',
    highlights: ['Diện tích rộng lớn ven biển', 'Kiến trúc Angkor chạm khắc tinh xảo', 'Cổng chùa đồ sộ rực rỡ sắc vàng'],
    createdAt: '2026-06-04T08:49:00.000Z',
    location: { lat: 9.2778, lng: 105.8278 },
    builtYear: '1887',
  },
  {
    id: 'chua-ong-met',
    title: 'Chùa Ông Met (Wat Bodhisalaraja)',
    province: 'Trà Vinh',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Khmer cổ kính và là trung tâm đào tạo Phật học của tỉnh.',
    body: 'Chùa Ông Met tọa lạc tại trung tâm thành phố Trà Vinh. Đây là một ngôi chùa cổ có lịch sử lâu đời từ năm 642 và trùng tu nhiều lần. Chùa nổi tiếng là trung tâm giáo dục, dịch thuật kinh điển và là trường trung cấp Phật học Nam tông Khmer lớn nhất tại Trà Vinh.',
    tag: 'Lịch sử',
    description: 'Di tích lịch sử văn hóa lâu đời, nơi lưu giữ tinh hoa giáo dục Phật học Khmer.',
    highlights: ['Lịch sử lâu đời từ năm 642', 'Trung tâm đào tạo Phật học Nam tông', 'Kiến trúc cột gỗ và mái ngói cổ kính'],
    createdAt: '2026-06-04T08:50:00.000Z',
    location: { lat: 9.9328, lng: 106.3422 },
    builtYear: 'Năm 642',
  },
  {
    id: 'chua-pothi-somron',
    title: 'Chùa Pôthi Somrôn',
    province: 'Cần Thơ',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Khmer cổ kính nằm bên dòng sông Ô Môn thơ mộng.',
    body: 'Chùa Pôthi Somrôn tọa lạc tại quận Ô Môn, thành phố Cần Thơ, được xây dựng từ năm 1735. Ngôi chùa nép mình bên dòng sông Ô Môn hiền hòa, xung quanh là những cây somrôn cổ thụ rợp bóng. Đây là ngôi chùa Khmer cổ nhất tại Cần Thơ, lưu giữ bảo tháp cổ cao vút và nhiều kinh sách cổ quý báu viết trên lá buông.',
    tag: 'Khám phá',
    description: 'Ngôi chùa cổ nhất của thành phố Cần Thơ mang vẻ đẹp thanh tịnh yên bình.',
    highlights: ['Xây dựng từ năm 1735', 'Lưu giữ bảo tháp cổ đá sa thạch', 'Kinh lá buông cổ quý hiếm'],
    createdAt: '2026-06-04T08:51:00.000Z',
    location: { lat: 10.1205, lng: 105.6261 },
    builtYear: '1735',
  },
  {
    id: 'chua-xa-ton',
    title: 'Chùa Xà Tón (Wat Xvayton)',
    province: 'An Giang',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa cổ nhất vùng Bảy Núi gắn liền với truyền thuyết khỉ.',
    body: 'Chùa Xà Tón tọa lạc tại thị trấn Tri Tôn, huyện Tri Tôn, tỉnh An Giang. Đây là ngôi chùa Khmer cổ nhất vùng Bảy Núi An Giang với tuổi đời hơn 200 năm. Tên gọi Xvayton gắn liền với truyền thuyết đàn khỉ hay đùa giỡn tại đây. Chùa sở hữu hồ nước lớn thơ mộng trước sân và lưu giữ số lượng kinh lá buông nhiều nhất Việt Nam.',
    tag: 'Kỷ lục',
    description: 'Ngôi chùa cổ lưu giữ nhiều bộ kinh trên lá buông nhất Việt Nam.',
    highlights: ['Lịch sử hơn 200 năm vùng Bảy Núi', 'Kỷ lục lưu giữ kinh lá buông cổ', 'Hồ sen lớn thơ mộng trong khuôn viên'],
    createdAt: '2026-06-04T08:52:00.000Z',
    location: { lat: 10.4131, lng: 105.0064 },
    builtYear: 'Thế kỷ XVIII',
  },
  {
    id: 'khu-khao-co-oc-eo',
    title: 'Khu di tích khảo cổ Óc Eo - Ba Thê',
    province: 'An Giang',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Dấu tích kinh thành cổ của vương quốc Phù Nam phồn thịnh 2000 năm trước.',
    body: 'Khu di tích Óc Eo nằm dưới chân núi Ba Thê, huyện Thoại Sơn, tỉnh An Giang. Nơi đây từng là thương cảng sầm uất và trung tâm văn hóa của Vương quốc Phù Nam cổ đại từ thế kỷ I đến thế kỷ VII. Các cuộc khai quật đã phát lộ nhiều nền móng đền đài gạch cổ, các hiện vật vàng, đá quý, tượng thần Hindu giáo và Phật giáo vô cùng quý giá.',
    tag: 'Di sản quốc gia',
    description: 'Di tích quốc gia đặc biệt lưu giữ nền văn minh Óc Eo rực rỡ.',
    highlights: ['Nền móng đền tháp gạch cổ', 'Bia đá chữ Phạn cổ', 'Hiện vật khảo cổ vàng, đá quý'],
    createdAt: '2026-06-04T08:53:00.000Z',
    location: { lat: 10.2797, lng: 105.1378 },
    builtYear: 'Thế kỷ II',
  },
  {
    id: 'chua-phu-ly-moi',
    title: 'Chùa Phù Ly Mới',
    province: 'Vĩnh Long',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa cổ Khmer nổi tiếng với nét chạm khắc gỗ rực rỡ.',
    body: 'Chùa Phù Ly Mới tọa lạc tại xã Đông Bình, thị xã Bình Minh, tỉnh Vĩnh Long. Ngôi chùa được xây dựng vào năm 1672, mang vẻ đẹp yên tĩnh thanh tịnh bên sông. Kiến trúc chánh điện nổi bật với hệ thống hoa văn đắp nổi sơn thếp vàng rực rỡ, chim thần Krud nâng cột chèo và các bích họa tường Phật giáo tinh tế.',
    tag: 'Khám phá',
    description: 'Ngôi chùa Khmer cổ nhất tỉnh Vĩnh Long với nghệ thuật điêu khắc gỗ độc đáo.',
    highlights: ['Xây dựng từ năm 1672 cổ kính', 'Hệ thống cột gỗ chánh điện chạm khắc', 'Bích họa sử thi đức Phật'],
    createdAt: '2026-06-04T08:54:00.000Z',
    location: { lat: 10.0267, lng: 105.8822 },
    builtYear: '1672',
  },
  {
    id: 'chua-sam-rong-ek',
    title: 'Chùa Săm Rông Ek',
    province: 'Trà Vinh',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa cổ linh thiêng bậc nhất Trà Vinh với tháp mộ cột đá.',
    body: 'Chùa Săm Rông Ek tọa lạc tại phường 8, thành phố Trà Vinh. Đây là một trong những ngôi chùa Phật giáo Nam tông Khmer lâu đời của Trà Vinh, nổi tiếng với sự linh thiêng. Khuôn viên chùa có những ngọn tháp mộ cổ xưa rêu phong, chánh điện sơn son thếp vàng uy nghi cùng hàng cột đá chạm nổi hình tượng rồng Naga.',
    tag: 'Tôn giáo',
    description: 'Điểm sinh hoạt tôn giáo tín ngưỡng linh thiêng của đồng bào Trà Vinh.',
    highlights: ['Các ngôi tháp mộ cổ rêu phong', 'Chánh điện chạm khắc tỉ mỉ', 'Hệ thống vườn cây sao cổ thụ'],
    createdAt: '2026-06-04T08:55:00.000Z',
    location: { lat: 9.9239, lng: 106.3533 },
    builtYear: 'Thế kỷ XVI',
  },
  {
    id: 'chua-koi-kong',
    title: 'Chùa Kôi Kông (Chùa Ông)',
    province: 'Kiên Giang',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa cổ ven sông mang kiến trúc Khmer sông nước Kiên Giang.',
    body: 'Chùa Kôi Kông tọa lạc tại huyện Gò Quao, tỉnh Kiên Giang. Chùa được xây dựng lâu đời, mang nét đặc trưng của vùng quê sông nước Kiên Giang. Ngôi chùa có kiến trúc hài hòa giữa nét Angkor cổ điển với các họa tiết đắp nổi, là nơi diễn ra các lễ hội đua ghe ngo nhộn nhịp của huyện Gò Quao vào dịp Ok Om Bok.',
    tag: 'Văn hóa',
    description: 'Trung tâm văn hóa tâm linh của đồng bào Khmer vùng Gò Quao Kiên Giang.',
    highlights: ['Nằm ven sông Gò Quao thơ mộng', 'Kiến trúc Angkor rực rỡ sắc màu', 'Trung tâm tổ chức đua ghe ngo của huyện'],
    createdAt: '2026-06-04T08:56:00.000Z',
    location: { lat: 9.6833, lng: 105.3167 },
    builtYear: 'Thế kỷ XVII',
  },
  {
    id: 'chua-o-mich',
    title: 'Chùa Ô Mịch (Sêrêy Kông Môg)',
    province: 'Trà Vinh',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Khmer cổ vùng nông thôn Trà Cú thanh tịnh.',
    body: 'Chùa Ô Mịch tọa lạc tại xã Châu Điền, huyện Cầu Kè, tỉnh Trà Vinh. Ngôi chùa mang nét bình dị thanh tịnh của vùng quê Nam Bộ. Với lối kiến trúc chánh điện truyền thống, chùa nổi bật nhờ các họa tiết đắp nổi Naga uốn lượn rực rỡ và những hàng cây thốt nốt vây quanh khuôn viên.',
    tag: 'Bình dị',
    description: 'Vẻ đẹp mộc mạc thanh tịnh của ngôi chùa Khmer vùng nông thôn Trà Vinh.',
    highlights: ['Hàng cây thốt nốt quanh chùa', 'Kiến trúc chánh điện mái ngói cong', 'Không gian đồng quê thanh bình'],
    createdAt: '2026-06-04T08:57:00.000Z',
    location: { lat: 9.8828, lng: 106.1822 },
    builtYear: 'Thế kỷ XVIII',
  },
  {
    id: 'tet-chol-chnam-thmay',
    title: 'Tết Chol Chnam Thmay',
    province: 'Sóc Trăng',
    category: 'Lễ hội truyền thống',
    type: 'intangible',
    subtitle: 'Lễ hội mừng năm mới lớn nhất của đồng bào Khmer Nam Bộ.',
    body: 'Chol Chnam Thmay là Tết cổ truyền đón năm mới của người Khmer, diễn ra vào khoảng giữa tháng 4 Dương lịch hằng năm. Lễ hội kéo dài 3 ngày nhằm cầu chúc năm mới mưa thuận gió hòa, mùa màng tươi tốt. Người dân tập trung đón thần năm mới Maha Songkran, đi chùa dâng cơm chúc phúc sư sãi, làm lễ đắp núi cát và thực hiện nghi thức tắm Phật cầu an.',
    tag: 'Lớn nhất',
    description: 'Lễ hội năm mới tưng bừng với các nghi thức tâm linh cầu bình an và may mắn.',
    highlights: ['Lễ đón thần Maha Songkran', 'Tục đắp núi cát cầu duyên', 'Nghi thức tắm Phật cầu an lành'],
    createdAt: '2026-06-04T08:58:00.000Z',
    location: { lat: 9.6008, lng: 105.9745 },
  },
  {
    id: 'nghe-thuat-du-ke',
    title: 'Nghệ thuật Sân khấu Dù Kê',
    province: 'Trà Vinh',
    category: 'Nghệ thuật biểu diễn',
    type: 'intangible',
    subtitle: 'Loại hình kịch hát dân gian độc đáo kết hợp âm nhạc, vũ đạo và sử thi.',
    body: 'Nghệ thuật Dù Kê (hay Lakhon Du Ke) ra đời vào những năm đầu thế kỷ XX tại Nam Bộ, là sự giao thoa nghệ thuật sân khấu độc đáo. Dù Kê kết hợp điệu múa Khmer truyền thống, âm nhạc dàn nhạc ngũ âm, lối hát tự sự đối đáp và cốt truyện dân gian hoặc sử thi Reamker. Sân khấu Dù Kê mang tính giáo dục đạo lý nhân văn sâu sắc.',
    tag: 'Di sản quốc gia',
    description: 'Di sản văn hóa phi vật thể quốc gia - linh hồn kịch nghệ Khmer Nam Bộ.',
    highlights: ['Lối hát tự sự giao duyên ngọt ngào', 'Dàn nhạc ngũ âm Pinpeat rộn ràng', 'Các câu chuyện sử thi Reamker thần thoại'],
    createdAt: '2026-06-04T08:59:00.000Z',
    location: { lat: 9.9347, lng: 106.3456 },
  },
  {
    id: 'nhac-ngu-am-pinpeat-khmer',
    title: 'Dàn nhạc Ngũ âm (Pinpeat)',
    province: 'Sóc Trăng',
    category: 'Nghệ thuật biểu diễn',
    type: 'intangible',
    subtitle: 'Dàn nhạc cổ truyền linh thiêng đệm cho các nghi lễ tôn giáo và múa cổ.',
    body: 'Dàn nhạc Ngũ âm (Pinpeat) là dàn nhạc truyền thống của người Khmer Nam Bộ. Dàn nhạc sử dụng 5 nhóm nhạc cụ làm từ các chất liệu đồng, sắt, gỗ, da và hơi thở (sáo). Nhạc ngũ âm có giai điệu rộn ràng, uy nghiêm, chuyên đệm cho các nghi lễ cúng bái tại chùa, kịch múa Rô Băm, Dù Kê và các điệu múa cổ truyền phum sóc.',
    tag: 'Linh hồn âm nhạc',
    description: 'Âm điệu linh thiêng hòa quyện giữa các chất liệu đồng, gỗ, da của nhạc cụ.',
    highlights: ['Dàn nhạc sử dụng nhạc cụ ngũ âm', 'Biểu diễn tại các ngày lễ chùa lớn', 'Giai điệu rộn rã uy nghiêm tâm linh'],
    createdAt: '2026-06-04T09:00:00.000Z',
    location: { lat: 9.6012, lng: 105.9734 },
  },
  {
    id: 'mua-apsara-khmer',
    title: 'Nghệ thuật Múa Apsara Khmer Nam Bộ',
    province: 'Trà Vinh',
    category: 'Nghệ thuật biểu diễn',
    type: 'intangible',
    subtitle: 'Điệu múa cổ điển cung đình uốn lượn mềm mại uyển chuyển.',
    body: 'Múa Apsara là điệu múa cổ điển có nguồn gốc hoàng cung Angkor cổ xưa. Các vũ nữ mặc trang phục dát vàng lộng lẫy, đeo vương miện đỉnh nhọn chóp và thực hiện các tư thế uốn cong ngón tay, bàn chân vô cùng mềm dẻo. Múa Apsara kể về thế giới thần thoại và ca ngợi vẻ đẹp thiên nhiên tươi đẹp.',
    tag: 'Nghệ thuật múa',
    description: 'Vũ điệu thần tiên uốn lượn uyển chuyển mang đậm nét điêu khắc Angkor cổ.',
    highlights: ['Động tác uốn ngón tay điêu luyện', 'Trang phục dát vàng rực rỡ lộng lẫy', 'Kể chuyện thần thoại Phật giáo Nam tông'],
    createdAt: '2026-06-04T09:01:00.000Z',
    location: { lat: 9.9347, lng: 106.3456 },
  },
  {
    id: 'dieu-kleng-khmer',
    title: 'Nghệ thuật làm Diều Kleng (Diều Sáo)',
    province: 'Sóc Trăng',
    category: 'Khác',
    type: 'intangible',
    subtitle: 'Thả diều Kleng đón gió chướng thổi kèm tiếng sáo vi vu.',
    body: 'Thả diều Kleng (diều sáo) là trò chơi dân gian và tri thức thủ công độc đáo của người Khmer Nam Bộ vào mùa khô (tháng 11 đến tháng 2 Âm lịch). Diều Kleng được làm từ tre trúc và giấy dán, gắn thêm bộ sáo tre trên đầu diều. Khi bay cao đón gió chướng thổi, sáo diều sẽ phát ra tiếng vi vu thanh bình vang khắp phum sóc.',
    tag: 'Đặc sắc',
    description: 'Tri thức làm diều tre gắn sáo trúc độc đáo ngân vang tiếng nhạc trên không.',
    highlights: ['Khung diều làm bằng tre trúc dẻo', 'Sáo trúc gắn đầu diều vi vu đón gió', 'Thả diều vào mùa khô gặt hái'],
    createdAt: '2026-06-04T09:02:00.000Z',
    location: { lat: 9.6008, lng: 105.9745 },
  },
  {
    id: 'le-cuoi-truyen-thong-khmer',
    title: 'Phong tục Cưới hỏi truyền thống người Khmer',
    province: 'Trà Vinh',
    category: 'Khác',
    type: 'intangible',
    subtitle: 'Nghi lễ hôn nhân truyền thống dài ngày đậm nét văn hóa mẫu hệ.',
    body: 'Lễ cưới của người Khmer Nam Bộ mang đậm nét văn hóa mẫu hệ truyền thống, thường được tổ chức tại nhà gái. Đám cưới kéo dài nhiều ngày với nhiều nghi lễ độc đáo: Lễ rước rể, Lễ cắt tóc tẩy trần (cắt đi những điều không tốt lành), Lễ buộc chỉ cổ tay chúc phúc cho cô dâu chú rể và Lễ xoay đèn cúng thần.',
    tag: 'Phong tục',
    description: 'Các nghi thức chúc phúc gia đình hạnh phúc theo truyền thống mẫu hệ xưa.',
    highlights: ['Nghi lễ tổ chức tại nhà gái', 'Lễ buộc chỉ cổ tay chúc phúc', 'Mâm quả bánh gừng, hoa cau rực rỡ'],
    createdAt: '2026-06-04T09:03:00.000Z',
    location: { lat: 9.9347, lng: 106.3456 },
  },
  {
    id: 'lam-banh-gung-khmer',
    title: 'Tri thức dân gian làm Bánh Gừng (Num Khnhei)',
    province: 'Sóc Trăng',
    category: 'Ẩm thực',
    type: 'intangible',
    subtitle: 'Món bánh cưới ngọt ngào mang biểu tượng tình nghĩa vợ chồng.',
    body: 'Bánh gừng (Num Khnhei) là món bánh ngọt truyền thống được làm từ bột nếp, trứng gà, men rượu và đường thốt nốt. Bánh được nặn khéo léo tạo hình giống củ gừng rồi đem chiên giòn, sau đó nhúng qua lớp nước đường thốt nốt vàng óng. Bánh thường xuất hiện trong mâm quả cưới hỏi và lễ Sen Dolta cầu chúc vợ chồng khăng khít ngọt ngào.',
    tag: 'Ẩm thực',
    description: 'Món bánh truyền thống hình củ gừng vàng óng mang ý nghĩa thủy chung gắn kết.',
    highlights: ['Nguyên liệu bột nếp đường thốt nốt', 'Tạo hình củ gừng nghệ thuật thủ công', 'Biểu tượng tình nghĩa vợ chồng trong đám cưới'],
    createdAt: '2026-06-04T09:04:00.000Z',
    location: { lat: 9.6008, lng: 105.9745 },
  },
  {
    id: 'gia-com-dep-truyen-thong',
    title: 'Tục giã Cốm dẹp truyền thống Khmer',
    province: 'Trà Vinh',
    category: 'Ẩm thực',
    type: 'intangible',
    subtitle: 'Giã nếp non rang nóng dâng cúng tạ ơn thần Mặt Trăng.',
    body: 'Cốm dẹp (Om Bok) là lễ vật quan trọng nhất trong lễ Ok Om Bok. Nếp non vừa ngậm sữa được rang nóng trong chảo đất nung, sau đó cho vào cối giã thủ công rồi sàng sảy sạch vỏ trấu. Cốm dẹp trộn với dừa nạo và đường thốt nốt tạo nên vị thơm dẻo bùi ngọt, dâng lên cúng Trăng để tạ ơn mùa màng ấm no.',
    tag: 'Tri thức dân gian',
    description: 'Nghi thức làm cốm từ hạt nếp non rang nóng thơm lừng phum sóc.',
    highlights: ['Rang nếp non trong chảo đất nung', 'Giã cốm thủ công nhịp nhàng đôi nam nữ', 'Món ăn trộn dừa nạo đường ngọt thơm'],
    createdAt: '2026-06-04T09:05:00.000Z',
    location: { lat: 9.9347, lng: 106.3456 },
  },
  {
    id: 'mua-trong-sadam',
    title: 'Nghệ thuật Múa trống Sa-dăm',
    province: 'Bạc Liêu',
    category: 'Nghệ thuật biểu diễn',
    type: 'intangible',
    subtitle: 'Điệu múa trống rộn rã khỏe khoắn của nam thanh niên phum sóc.',
    body: 'Múa trống Sa-dăm là điệu múa trống truyền thống đầy sức sống của người Khmer. Người múa đeo chiếc trống Sa-dăm hình ống cần dài trước ngực, vừa gõ trống tạo nhịp điệu rộn rã khỏe khoắn, vừa thực hiện các động tác múa tay chân nhịp nhàng, nhào lộn điêu luyện trong các đoàn diễu hành lễ hội lớn.',
    tag: 'Sức sống',
    description: 'Vũ điệu múa trống diễu hành rộn rã khuấy động không khí hội hè.',
    highlights: ['Người múa đeo trống gỗ Sa-dăm', 'Các động tác võ thuật nhào lộn khỏe khoắn', 'Khuấy động đoàn diễu hành năm mới, lễ hội'],
    createdAt: '2026-06-04T09:06:00.000Z',
    location: { lat: 9.2941, lng: 105.7234 },
  },
  {
    id: 'le-hoi-phuoc-bien',
    title: 'Lễ hội cúng Phước Biển (Thoát Yà)',
    province: 'Sóc Trăng',
    category: 'Lễ hội truyền thống',
    type: 'intangible',
    subtitle: 'Lễ hội tạ ơn biển cả mang lại tôm cá no ấm cho đồng bào ven biển.',
    body: 'Lễ hội cúng Phước Biển (Thoát Yà) diễn ra vào tháng 2 âm lịch hằng năm tại thị xã Vĩnh Châu, tỉnh Sóc Trăng. Đây là nghi lễ tạ ơn biển khơi đã ban tặng nguồn thủy hải sản dồi dào nuôi sống con người phum sóc ven biển. Lễ hội trang nghiêm với lễ cầu an chư tăng, lễ thả thuyền giấy ra biển khơi và hát dù kê thâu đêm.',
    tag: 'Ven biển',
    description: 'Lễ hội tạ ơn biển khơi đặc sắc của đồng bào Khmer sinh sống ven biển Sóc Trăng.',
    highlights: ['Nghi lễ thả thuyền giấy ra khơi cầu an', 'Biểu diễn kịch hát Dù Kê thâu đêm', 'Địa điểm vùng ven biển Vĩnh Châu Sóc Trăng'],
    createdAt: '2026-06-04T09:07:00.000Z',
    location: { lat: 9.3242, lng: 106.0122 },
  },
  {
    id: 'le-nhap-ha-chol-vossa',
    title: 'Lễ nhập hạ (Chol Vossa)',
    province: 'Sóc Trăng',
    category: 'Lễ hội truyền thống',
    type: 'intangible',
    subtitle: 'Lễ nhập hạ ba tháng cấm túc tụng niệm của các vị sư sãi.',
    body: 'Lễ Chol Vossa diễn ra vào giữa tháng 6 âm lịch, đánh dấu sự bắt đầu của 3 tháng mùa an cư kiết hạ. Trong 3 tháng này, các vị sư sãi không được đi nghỉ qua đêm ngoài chùa mà phải tập trung tu học học pháp, tụng niệm. Phật tử phum sóc dâng nến lớn (Nến nhập hạ) và đồ nhu yếu phẩm cúng chùa để cầu phước tích đức.',
    tag: 'Tôn giáo',
    description: 'Nghi lễ khởi đầu ba tháng mùa an cư tu học linh thiêng tại chùa Khmer.',
    highlights: ['Dâng cặp nến nhập hạ khổng lồ', 'Quyên góp nhu yếu phẩm cúng chùa', 'Ba tháng mùa chay tịnh tu học cầu an'],
    createdAt: '2026-06-04T09:08:00.000Z',
    location: { lat: 9.6012, lng: 105.9734 },
  },
  {
    id: 'kinh-la-buong-khmer',
    title: 'Tri thức viết Kinh trên lá buông (Kinh lá buông)',
    province: 'An Giang',
    category: 'Khác',
    type: 'intangible',
    subtitle: 'Di sản viết chữ Khmer cổ trên lá cây buông sấy khô cực kỳ bền bỉ.',
    body: 'Viết kinh trên lá buông (Sastrapát) là tri thức dân gian độc đáo của các nhà sư Khmer vùng Bảy Núi. Lá buông non được chọn lọc cắt về, phơi ép khô sấy rồi dùng bút sắt nhọn khắc khắc chữ Khmer cổ lên bề mặt lá, sau đó dùng mực đen quét phủ nổi bật nét chữ. Những bộ kinh lá buông có độ bền hàng trăm năm không mục nát.',
    tag: 'Di sản quý',
    description: 'Tri thức khắc chữ trên lá cây buông khô lưu truyền kinh điển hàng trăm năm cổ xưa.',
    highlights: ['Chọn lọc lá buông non ép khô', 'Khắc chữ bằng bút sắt thủ công', 'Kinh sách có tuổi đời trăm năm không hỏng'],
    createdAt: '2026-06-04T09:09:00.000Z',
    location: { lat: 10.4282, lng: 105.0256 },
  },
  {
    id: 'tro-choi-di-ca-kheo',
    title: 'Trò chơi dân gian đi Cà kheo Khmer',
    province: 'Sóc Trăng',
    category: 'Khác',
    type: 'intangible',
    subtitle: 'Trò chơi giữ thăng bằng trên hai cây tre cao nhộn nhịp ngày hội.',
    body: 'Trò chơi đi cà kheo (được làm từ hai cây tre thẳng cao tầm 1.5 - 2 mét, có bệ đỡ chân) là trò chơi thể thao dân gian phổ biến tại các hội làng phum sóc. Người chơi giữ thăng bằng di chuyển đi nhanh, chạy hoặc đua tài với nhau, thể hiện sự khéo léo khỏe khoắn của thanh niên Khmer ngày xuân.',
    tag: 'Thể thao',
    description: 'Môn thi tài thăng bằng khéo léo tưng bừng tiếng reo hò cổ vũ ngày hội phum sóc.',
    highlights: ['Cà kheo làm bằng tre gai già dẻo', 'Trò chơi rèn luyện sức bền giữ thăng bằng', 'Cuộc thi chạy cà kheo tốc độ cao'],
    createdAt: '2026-06-04T09:10:00.000Z',
    location: { lat: 9.6008, lng: 105.9745 },
  },
  {
    id: 'nha-san-truyen-thong',
    title: 'Tục làm Nhà sàn truyền thống Khmer Nam Bộ',
    province: 'An Giang',
    category: 'Khác',
    type: 'tangible',
    subtitle: 'Kiến trúc nhà sàn gỗ tránh lũ và giữ sự thoáng mát vùng Nam Bộ.',
    body: 'Tục làm nhà sàn gỗ truyền thống của người Khmer xưa gắn liền với địa hình sông nước và mùa lũ miền Tây. Nhà sàn được dựng bằng gỗ tốt, mái ngói cong vuốt tranh tre, sàn nhà cách mặt đất khoảng 1.5 - 2 mét để tránh ẩm ướt thú dữ và lũ lụt đổ về. Dưới sàn là nơi để nông cụ và sinh hoạt mát mẻ ban ngày.',
    tag: 'Đời sống',
    description: 'Kiến trúc nhà ở độc đáo thích nghi hoàn hảo với khí hậu mùa lũ sông nước Nam Bộ.',
    highlights: ['Dựng bằng cột gỗ sàn cách đất', 'Mái ngói hai mái dốc tránh mưa lớn', 'Kiến trúc thích nghi mùa lũ lụt Nam Bộ'],
    createdAt: '2026-06-04T09:11:00.000Z',
    location: { lat: 10.4282, lng: 105.0256 },
    builtYear: 'Thế kỷ XIX',
  },
  {
    id: 'trang-phuc-sampot',
    title: 'Tri thức dệt trang phục truyền thống Săm-pốt',
    province: 'Trà Vinh',
    category: 'Khác',
    type: 'intangible',
    subtitle: 'Vải quấn Sampot lụa tơ tằm hoa văn thổ cẩm Khmer tinh xảo.',
    body: 'Săm-pốt (Sampot) là trang phục truyền thống của người Khmer Nam Bộ, đặc biệt diện vào các dịp lễ tết cưới hỏi. Sampot là tấm vải lụa tơ tằm dệt thủ công hoa văn thổ cẩm tinh tế dài khoảng 3 mét, quấn quanh hông và luồn qua hai chân tạo thành chiếc quần thụng. Nghệ thuật dệt và quấn Sampot thể hiện tri thức thẩm mỹ cổ xưa.',
    tag: 'Trang phục',
    description: 'Tấm lụa tơ tằm dệt hoa văn tinh xảo biến hóa thành trang phục truyền thống.',
    highlights: ['Chất liệu lụa tơ tằm dệt tay', 'Cách quấn quấn thắt vải nghệ thuật', 'Sử dụng tại các ngày hội cưới lớn phum sóc'],
    createdAt: '2026-06-04T09:12:00.000Z',
    location: { lat: 9.9347, lng: 106.3456 },
  },
  {
    id: 'canh-sim-lo-khmer',
    title: 'Tri thức nấu Canh Sim-lo truyền thống',
    province: 'Trà Vinh',
    category: 'Ẩm thực',
    type: 'intangible',
    subtitle: 'Món canh rau rừng nấu mắm bò hóc thanh mát đặc trưng.',
    body: 'Canh Sim-lo (hay canh thụt) là món canh dân dã mộc mạc đặc trưng nhất của người Khmer Nam Bộ. Canh được nấu từ nước dùng cốt mắm Prahok (bò hóc), kết hợp các loại rau rừng bản địa như lá chúc, bắp chuối, rau ngót, cà dĩa và cá lóc đồng hoặc thịt. Món canh có vị ngọt thanh cay nồng ấm bụng, rất thích hợp giải nhiệt.',
    tag: 'Ẩm thực',
    description: 'Món canh dân dã đậm đà vị mắm bò hóc hòa quyện cùng nhiều loại rau rừng dã ngoại.',
    highlights: ['Nước dùng gia vị mắm Prahok bò hóc', 'Sử dụng lá chúc và rau rừng bản địa', 'Món canh giải nhiệt ấm lòng ngày hè sông nước'],
    createdAt: '2026-06-04T09:13:00.000Z',
    location: { lat: 9.9347, lng: 106.3456 },
  },
  {
    id: 'chua-vay-ton',
    title: 'Chùa Vàm Ray',
    province: 'Trà Vinh',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Ngôi chùa Khmer dát vàng rực rỡ và lộng lẫy nhất miền Tây.',
    body: 'Chùa Vàm Ray tọa lạc tại huyện Trà Cú, tỉnh Trà Vinh. Đây là ngôi chùa Phật giáo Nam tông Khmer lớn nhất Việt Nam mang đậm phong cách Angkor. Toàn bộ ngôi chùa được sơn thếp vàng lộng lẫy từ cổng chùa, bảo tháp đến vòm mái chánh điện, mang lại vẻ nguy nga lộng lẫy như một hoàng cung dát vàng giữa đồng quê Trà Vinh.',
    tag: 'Dát vàng',
    description: 'Ngôi chùa Khmer dát vàng rực rỡ tráng lệ nhất Việt Nam tọa lạc tại Trà Cú Trà Vinh.',
    highlights: ['Dát vàng lộng lẫy toàn bộ chùa', 'Tượng Phật nằm ngoài trời dài 54m', 'Kiến trúc Angkor chánh điện nguy nga'],
    createdAt: '2026-06-04T09:14:00.000Z',
    location: { lat: 9.6917, lng: 106.2822 },
    builtYear: 'Trùng tu năm 2004',
  },
  {
    id: 'chua-khang-nha-bac-lieu',
    title: 'Chùa Xiêm Cán Cổ (Wat Xiêm Cán)',
    province: 'Bạc Liêu',
    category: 'Kiến trúc tôn giáo',
    type: 'tangible',
    subtitle: 'Khuôn viên chánh điện cũ và tháp cốt linh thiêng trăm tuổi Bạc Liêu.',
    body: 'Chùa Xiêm Cán Cổ (Wat Xiêm Cán Cũ) là cụm kiến trúc tháp cốt và chánh điện cũ nép mình bên cạnh chánh điện mới khánh thành của chùa Xiêm Cán. Nơi đây rêu phong cổ kính lưu giữ những bia mộ đá trăm tuổi và các cột đá đắp nổi Naga cổ xưa, mang vẻ yên tĩnh linh thiêng trầm lặng thu hút du khách hoài cổ.',
    tag: 'Hoài cổ',
    description: 'Khu mộ tháp cổ rêu phong trăm tuổi linh thiêng trầm mặc tại Xiêm Cán Bạc Liêu.',
    highlights: ['Các tháp mộ trăm năm tuổi cổ kính', 'Nền gạch cổ rêu phong trầm mặc', 'Nét điêu khắc gỗ cổ xưa được lưu giữ tốt'],
    createdAt: '2026-06-04T09:15:00.000Z',
    location: { lat: 9.2778, lng: 105.8278 },
    builtYear: '1887',
  },
];

export function getHeritageById(id: string) {
  return heritageItems.find((item) => item.id === id);
}

export function getHeritageCover(coverImage?: string, type?: 'tangible' | 'intangible'): string {
  if (coverImage && coverImage.trim().length > 0) return coverImage.trim();
  return type === 'intangible'
    ? 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80'
    : 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=600&q=80';
}